name: System Info Workflow

on:
  push:

jobs:
  system-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print system information
        run: |
          echo "Current Directory:"
          pwd
          
          echo "----------------------"
          echo "OS Information:"
          uname -a
          
          echo "----------------------"
          echo "Current Date:"
          date